### ISSUE TITLE
tvOS?

### ISSUE THREAD

**Issue by technoplato** [Dimillian/MovieSwiftUI#41]
Just curious why tvOS isn't supported out of the box here by SwiftUI.

Was this a conscious decision or were there things you wanted to do that tvOS didn't let you?

**Comment by Dimillian** [comment]
TvOS is supported by SwiftUI. But like a Watch App, you need to make a separate target as it use different SwiftUI components. For iOS/macOS I've been able to almost the same UX thanks to Catalyst. For tvOS I'll need to do a completely different UX. I can reuse most of the code and just have to do some specific views. So it'll happen at some point :)

**Comment by technoplato** [comment]
Awesome. If you have any designs laying around or inspiration I’d love to
help with a PR. I just had a client ask for a rewrite of their tvOS and iOS
apps so figured SwiftUI was the way to go.

Would you be interested in something like that?

**Comment by Dimillian** [comment]
Actually I don't, and that's why I'm procrastinating on it. Basically the AppleTV build in TV app is very very good. 
The only thing I could do better is information surfacing. Because Apple don't give much information on each movies. So the movie detail view is the interesting part. Would love to have some time to actually commit to it.
