### ISSUE TITLE
The hidden performance issue of single store, especially in NavigationView

### ISSUE THREAD

**Issue by ghost** [Dimillian/MovieSwiftUI#47]
I applied your single store concept  into my project and found some performance issues. Here is my example

####  Background
1. `NextUpRootView` is the root navigation view
2. Click navigation item to push `RaceCard`. In `RaceCard`, fetch racing data via `getRaceCard`
3. Both `NextUpRootView` and `RaceCard` have `@EnvironmentObject var store: Store`

#### Problem
- NextUpRootView comes useless re-rendering even I'm on `RaceCard` after a `getRaceCard` operation. This could be a performance problem if navigation view comes a big stack(views). In my application, it also comes a very strange behavior:  when i'm on `RaceCard` page and execute `getRaceCard`, the app automatically pop back to `NextUpRootView` view;
- `@EnvironmentObject var store: Store` is the evil. Because as long as our state changes, all view that have this has to be rendered again

#### Code snippets
``` 
// root view controller

struct NextUpRootView: View {
    @EnvironmentObject var store: Store
    private var racing: AppState.Racing { store.appState.racing }
    ...

    var body: some View {
        NavigationView {
            VStack {
                NavigationLink(destination: RaceCard(data: self.raceCardData))
    }
}

// race card

struct RaceCard: View {
    
    @EnvironmentObject private var store: Store
    @ObservedObject var viewModel = RaceCardModel()
    
    init(data: VRaceCard) {
        self.viewModel.meetingId = data.meetingId
        self.viewModel.raceId = data.raceId
        self.viewModel.selectedRaceNumber = "\(data.raceNumber - 1)"
    }

    var body: some View {
        VStack(spacing: 0) {
            RaceTable(selectedProductGroupId: viewModel.selectedProductGroupId, raceId: viewModel.raceId)
        }
            .onReceive(viewModel.$selectedRaceNumber, perform: { _ in
                self.getRaceCard()
            })
    }
}

extension RaceCard {
    private func getRaceCard() {
        store.dispatch(.racing(.getRacecard(raceId: viewModel.raceId)))
    }
 
}

**Comment by Dimillian** [comment]
It's a known issue of this architecture. You can take a look at https://github.com/pointfreeco/swift-composable-architecture which offer much more features and allow to connect the view to only part of the store on a targeted set of diff.

**Comment by Andhar7** [comment]
Gratitude....Sent using the WEB.DE mail appOn 15.11.20 at 09:12, Thomas Ricouard wrote:
                
            
            
                
                    From: "Thomas Ricouard" <notifications@github.com>Date: 15 November 2020To: "Dimillian/MovieSwiftUI" <MovieSwiftUI@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Subject: Re: [Dimillian/MovieSwiftUI] The hidden performance issue of single store, especially in NavigationView (#47)
                
                
It's a known issue of this architecture. You can take a look at https://github.com/pointfreeco/swift-composable-architecture which offer much more features and allow to connect the view to only part of the store on a targeted set of diff.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Dimillian/MovieSwiftUI/issues/47#issuecomment-727532519",
"url": "https://github.com/Dimillian/MovieSwiftUI/issues/47#issuecomment-727532519",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
